### ISSUE TITLE
feature request

### ISSUE THREAD

**Issue by JeffWScott** [beyonk-adventures/svelte-intercom#3]
I would like access to the intecom methods such as 'open'

Can you expose those please?

https://developers.intercom.com/installing-intercom/docs/intercom-javascript

**Comment by JeffWScott** [comment]
Also your github Sponser option doesn't seem to be working.

**Comment by antony** [comment]
Yep I have to do a bunch of stuff to make it work :)

I'll expose the methods asap - I also require these :)

**Comment by JeffWScott** [comment]
haha, thanks @antony

**Comment by antony** [comment]
@JeffWScott give that a go :)

Github sponsors accepted me - but now have to approve my profile! Getting paid is hard huh? :D
